### ISSUE TITLE
fix: whisper_ggml_plus v1.3.1 fails to build on Android with CMake errors

### ISSUE THREAD

**Issue by omartinma** [divinevideo/divine-mobile#1568]
## Summary
The `whisper_ggml_plus` package (v1.3.1) fails to build on Android with CMake configuration and compilation errors, blocking Android app builds entirely. The package builds successfully on iOS/macOS.

The `whisper_ggml_plus` dependency was introduced in PR #1495 (feat: collabs grid, watermark download, save original, and startup perf) for on-device subtitle generation functionality

## Environment
- **Package version:** whisper_ggml_plus ^1.3.1
- **Platform:** Android
- **NDK versions tested:** 27.0.12077973, 28.2.13676358, 29.0.13113456
- **Build tools:** CMake 3.22.1, Gradle
- **App version:** Latest (main branch)

## Steps to Reproduce
1. Ensure `whisper_ggml_plus: ^1.3.1` is in `mobile/pubspec.yaml` (line 180)
2. Run `flutter clean && flutter pub get`
3. Run `flutter build apk` or `flutter run` targeting Android device/emulator
4. Observe build failure during CMake configuration

## Actual Result
Build fails with multiple CMake errors:

**Error 1 - No sources (initial):**
```
CMake Error at CMakeLists.txt:27 (add_library):
  No SOURCES given to target: whisper
```

**Root cause:** The package's `CMakeLists.txt` has incorrect directory paths. It looks for sources in `src/*.cpp` and `src/ggml-cpu/*.cpp`, but the actual files are located in `src/src/*.cpp` and `src/ggml/src/ggml-cpu/*.cpp`.

**Error 2 - Missing headers (after patching paths):**
```
fatal error: 'ggml-impl.h' file not found
fatal error: 'ggml-common.h' file not found  
fatal error: 'ggml-backend-impl.h' file not found
```

**Error 3 - Missing defines:**
```
error: use of undeclared identifier 'GGML_VERSION'
error: use of undeclared identifier 'GGML_COMMIT'
```

## Expected Result
- Package should build successfully on Android
- Android builds should complete without errors
- Subtitle generation feature should work on all platforms

## Regression?
Unknown - first time building with this package version on Android.

## Evidence
<details>
<summary>Full build output showing CMake errors</summary>

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':whisper_ggml_plus:configureCMakeRelease[arm64-v8a]'.
> [CXX1429] error when building with cmake using /Users/.../whisper_ggml_plus-1.3.1/android/src/whisper/CMakeLists.txt
  
  CMake Error at CMakeLists.txt:27 (add_library):
    No SOURCES given to target: whisper
```

After patching `CMakeLists.txt` to fix paths:
```
fatal error: 'ggml-impl.h' file not found
fatal error: 'ggml-common.h' file not found
fatal error: 'ggml-backend-impl.h' file not found
```
</details>

## Root Cause Analysis
The `whisper_ggml_plus` v1.3.1 package has a broken Android build configuration:

1. **Incorrect CMakeLists.txt paths:** The `file(GLOB)` commands reference wrong directories
2. **Missing include paths:** Required GGML internal headers are not in the include path
3. **Incomplete package structure:** Critical header files may be missing from the Android distribution

The package appears to have been tested primarily on iOS/macOS where it works correctly with the Podfile configuration in `mobile/macos/Podfile`.

## Impact
- **Severity:** High - Blocks all Android development builds
- **Affected feature:** On-device subtitle generation
- **Related files:**
  - `mobile/pubspec.yaml:180` - dependency declaration
  - `mobile/lib/services/whisper_transcription_service.dart` - service implementation
  - `mobile/lib/services/subtitle_generation_service.dart` - integration
  - `mobile/test/services/subtitle_generation_service_test.dart` - test coverage

## Attempted Solutions
1. ✅ Updated NDK from 28.2 → 29.0.13113456 (backward compatible)
2. ✅ Cleaned Flutter cache and ran `flutter pub cache repair`
3. ✅ Patched `CMakeLists.txt` in pub cache to fix directory paths
4. ❌ Still fails with missing headers and incomplete package structure

## External Package Issue
This appears to be a bug in the upstream package. Issue should be reported to whisper_ggml_plus maintainers at https://github.com/DDULDDUCK/whisper_ggml_plus
