### PR TITLE
fix(perf): keep developer builds out of the production Firebase Performance dataset

### PR DESCRIPTION
**Pull request by hm21**
## Description

Firebase Performance collection was enabled unconditionally, so every debug and profile build reported into the production dataset alongside real users. Developer builds are several times slower than release, and once the data has landed nothing distinguishes them except the `pubspec.yaml` build number — which store builds never carry, because Codemagic overrides `--build-number` with `Play latest + 1`.

That is not a theoretical concern. It is one of the three confounds that produced the headline figure in #7123: local builds were 9.5% of the 1.0.19 `_app_start` sample at a p50 of **919 ms**, against ~100 ms for the same phone model on a store build. iOS is affected the same way (build 819: 80 events, 2 devices, p50 891 ms).

Two layers, because neither is sufficient alone:

**Dart gate** — `PerformanceMonitoringService.collectionEnabled` is now `kReleaseMode`. Deliberately stricter than the `!kDebugMode` gate `CrashReportingService` uses: a profile build is a developer device too, and its timings land in the same dataset as real users rather than in a separate bucket. The flag is asserted on every launch rather than skipped when collection is off — the SDK persists it, so a device that ran an earlier build keeps reporting until something actively sets it back to `false`.

**Native deactivation** — the Dart gate cannot suppress `_app_start`, which is the trace #7123 was read from, because it is captured natively before Dart runs.

The native half is also the fragile half — `Debug.xcconfig`, `Profile.xcconfig`, and `Release.xcconfig` are Flutter template files that a scaffolding repair overwrites without saying so — so both manifests, the plist indirection, the Runner Profile → `Profile.xcconfig` wiring, and the build-setting values are pinned by tests. iOS profile builds deactivate natively via `Profile.xcconfig` (wired in `Runner.xcodeproj`); Android profile builds use the profile source-set manifest.

`mobile/docs/NETWORK_PERFORMANCE_MONITORING.md` is updated in the same change: its "Verifying a change" step 2 told you a LOCAL debug run exercises the path end to end and weighed the cost of `localhost` patterns landing in the project. Deactivating developer builds removes both halves of that, so the step now says what it actually proves and how to opt a single run back in.

### Why `_deactivated` and not `_enabled=false`

Both SDKs resolve in the same order: deactivation first (early return), then the persisted device cache, then the manifest/plist default. `_enabled=false` therefore sits on the bottom rung and loses to the cache — and every developer device that ran a build predating this PR has `true` cached there, which is exactly the population that needs silencing. `_deactivated` wins outright and takes effect on the first launch.

Verified against the actual SDK sources rather than the docs: `ConfigResolver.getIsPerformanceCollectionEnabled` in `firebase-perf` 22.0.5 (bytecode) and `FPRConfigurations.m` in `FirebasePerformance` 12.9.0.

The trade-off is that runtime re-enabling becomes impossible in those builds. To collect performance data from a local build — e.g. to verify new instrumentation — undo the native switch for that platform **and** flip `PerformanceMonitoringService.collectionEnabled` to `true`. Either one alone leaves collection off: the Dart gate re-asserts `false` on every launch and the SDK persists it, so removing the native switch just falls through to the cache that gate wrote. Noted at all three places a reader might start from — the debug manifest, `Debug.xcconfig`, and `mobile/docs/NETWORK_PERFORMANCE_MONITORING.md`.

### Why iOS goes through a build setting

There is one `Info.plist` for all configurations, so the value comes from `FIREBASE_PERFORMANCE_COLLECTION_DEACTIVATED`. `FPRConfigurations` reads the key through `-boolValue`, so a string from `$(...)` substitution works — checked empirically, including that `""` reads as `NO`.

The polarity is chosen for that empty case: if the setting ever goes missing the value expands to an empty string, which reads as `NO`, so the failure mode is *production keeps reporting* rather than a silent loss of production data. The inverse key would fail the other way and we would not notice for weeks.

## Out of Scope

- **The actual regression in #7123.** That issue is now reframed: device-controlled, 1.0.19 is ~15% *faster* than 1.0.15, and the real regression is ~14% between 1.0.17 and 1.0.19 caused by the Impeller switch in #6483. That was a deliberate trade-off (the chroma-key preview needs `ui.ImageFilter.shader`, which Skia does not implement), so it needs a product call, not a revert in this PR. #7123 stays open for it.

- **Historical data is still polluted.** This stops new contamination; it cannot clean what has landed. Past comparisons need filtering to store build numbers, and the corrected query is in #7123.

- **TestFlight builds still report.** They are genuine release builds, so the release-only gate does not exclude them by design.

## Verification

- `flutter analyze lib test` — no issues
- `flutter test test/services/performance_monitoring_service_test.dart` — 16/16 pass
- Dart gate test proven able to fail: flipping the gate to `true` yields `Expected: false / Actual: <true>`
- Native-config tests proven able to fail one at a time, by mutating the file each reads: `Debug.xcconfig` to `NO`, the profile manifest to `false`, the plist to a literal instead of `$(...)`, and a deactivation added to the release manifest. Each mutation failed exactly one test.
- `plutil -lint ios/Runner/Info.plist` — OK; `plutil -extract` confirms the key resolves to the build setting
- All three touched Android manifests parse as valid XML
- `-[NSString boolValue]` semantics confirmed by compiling against Foundation: `"YES"`→YES, `"NO"`→NO, `""`→NO

**Not yet verified on a device.** The behaviour this changes is only observable in the Firebase Performance dataset, so confirming it means installing a debug build and checking that no new `_app_start` events appear under a non-store build number. Worth doing on the Galaxy before this leaves draft.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [x] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

**Related Issue:** Relates to #7123

### CODE REVIEW

**Review by dcadenas — APPROVED** [review]
Debug and profile builds no longer pollute the production Firebase Performance dataset. Native deactivation covers `_app_start`; the Dart release-only gate covers the rest.

### Changes I pushed

- Wired Runner Profile to `Profile.xcconfig` with `FIREBASE_PERFORMANCE_COLLECTION_DEACTIVATED=YES`, so iOS profile builds deactivate on first launch like Android.
- Pinned that wiring and the Profile build setting in tests.

### Checks

- `flutter test test/services/performance_monitoring_service_test.dart` (16/16)
- `flutter analyze` on the touched Dart files
- CI on `49392edb2`: Mobile CI, Analyze, Format, Generated Files, all test shards green
